"""
Data models for the Researcher Agent.
"""
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field

class ReportType(str, Enum):
    """The type of output report to generate."""
    QUICK_SUMMARY = "quick_summary"
    DEEP_DIVE = "deep_dive"
    INSTA_EXPERT = "insta_expert"

class ResearchTask(BaseModel):
    """A specific dimension of the topic to investigate."""
    id: str = Field(..., description="Unique ID for the task")
    description: str = Field(..., description="What specifically needs to be researched")
    queries: List[str] = Field(..., description="Search queries to execute")
    source_type: str = Field("open_web", description="Type of source: 'open_web' or 'authenticated'")

    class Config:
        frozen = True

class ResearchPlan(BaseModel):
    """The master plan generated by the Orchestrator."""
    topic: str
    sub_tasks: List[ResearchTask]
    key_questions: List[str] = Field(..., description="Crucial questions the report must answer")
    estimated_tokens: int = Field(0, description="Estimated complexity/cost")

class ResearchFinding(BaseModel):
    """A piece of information found by a Scout."""
    source_url: str
    content: str
    relevance_score: float = Field(..., ge=0, le=1.0)
    key_fact: str

class ResearchReport(BaseModel):
    """The final synthesized output."""
    title: str
    executive_summary: str
    sections: List[dict]
    references: List[str]
